apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: front-end-pvc
  labels:
    app: front-end
    zadanie: kubernetes
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

