apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    zadanie: kubernetes
spec:
  ports:
  - name: flask-port
    port: 80
    targetPort: 5000
  selector:
    app: front-end
  type: LoadBalancer

