apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    zadanie: kubernetes
  name: redis
spec:
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
