apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    app: redis
    zadanie: kubernetes
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce

