apiVersion: v1
kind: ServiceAccount
metadata:
  name: all-seeing-eye
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: see-all-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: all-seeing-eye
  namespace: default
