apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-pods
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pods-seeing-eye
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: see-namespaced-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-pods
subjects:
- kind: ServiceAccount
  name: pods-seeing-eye
  namespace: default
